### ISSUE TITLE
actions/upload-artifact@v3 is not supported anymore

### ISSUE THREAD

**Issue by o01eg** [bend-n/godot-actions#10]
### What happened?

When I trying to use export actions I got error:

```
 Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

As I see in code it really still used https://github.com/bend-n/godot-actions/blob/287aaf38105bb89f555ca6fb911e82e66c0b5b59/.github/actions/export/action.yml#L59C13-L59C39

### Workflow

```YAML
name: "Android"

on:
  workflow_call:
jobs:
  generate-godot-api:
    name: Generate Godot API
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/bend-n/godot:3.5.2
    steps:
      - name: Setup
        uses: bend-n/godot-actions/.github/actions/setup-godot@main
        env:
          GODOT_VERSION: 3.5.2
      - name: Generate API file
        run: |
          timeout 1m godot --no-window --disable-render-loop --video-driver Dummy --gdnative-generate-json-api godot-api.json
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: godot-api
          path: godot-api.json
          if-no-files-found: error
          retention-days: 1
  android:
    name: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: generate-godot-api
    strategy:
      matrix:
        arch: [x86, x86_64, armeabi-v7a, arm64-v8a]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Dowload Godot API
        uses: actions/download-artifact@v4
        with:
          name: godot-api
          path: .
      - name: Download SDK
        id: download-sdk
        uses: suisei-cn/actions-download-file@v1.4.0
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v14/FreeOrionSDK_14_Android-${{ matrix.arch }}.zip
          target: ../
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r24
          add-to-path: false
      - name: Configure
        run: |
          unzip -q ../${{ steps.download-sdk.outputs.filename }} -d ..
          GODOT_API_JSON=$(realpath godot-api.json)
          mkdir build
          pushd build
          FO_SDK=$(realpath ../..)
          cmake -DANDROID_ABI=${{ matrix.arch }} -DANDROID_PLATFORM=24 -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DCMAKE_CXX_FLAGS=-std=c++14 -DANDROID_ALLOW_UNDEFINED_SYMBOLS=Off -DBUILD_SERVER=OFF -DBUILD_AI=OFF -DBUILD_CLIENT_GG=OFF -DBoost_INCLUDE_DIR=${FO_SDK}/include/ -DBoost_USE_STATIC_LIBS=On -DBoost_LIBRARY_DIR=${FO_SDK}/lib/ -DBUILD_CLIENT_GODOT=On -DICUI18N_LIBRARY=${FO_SDK}/lib/libicui18n.a -DICUUC_LIBRARY=${FO_SDK}/lib/libicuuc.a -DICUDATA_LIBRARY=${FO_SDK}/lib/libicudata.a -DICONV_LIBRARY=${FO_SDK}/lib/libiconv.so -DPython3_LIBRARY=${FO_SDK}/lib/libpython3.9.a -DPython3_INCLUDE_DIR=${FO_SDK}/include/python3.9/ -DGODOT_CUSTOM_API_FILE=${GODOT_API_JSON} ..
      - name: Build
        run: |
          pushd build
          cmake --build . -- -j2
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: android-binaries-${{ matrix.arch }}
          path: godot/bin/
          if-no-files-found: error
          retention-days: 1
  merge-binaries:
    name: Merge binaries
    runs-on: ubuntu-latest
    needs: android
    steps:
      - name: Merge binaries
        uses: actions/upload-artifact/merge@v4
        with:
          name: android-binaries
          pattern: android-binaries-*
          delete-merged: true
          retention-days: 1
  export-android:
    name: Export Android
    runs-on: ubuntu-22.04
    needs: merge-binaries
    container:
      image: ghcr.io/bend-n/godot:3.5.2
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup
        uses: bend-n/godot-actions/.github/actions/setup-godot@main
        env:
          GODOT_VERSION: 3.5.2
      - name: Download python library
        id: download-python-lib
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v14/python39.zip
          target: ../
      - name: Place resources
        run: |
          mkdir -p godot/default/python/lib/
          cp ../${{ steps.download-python-lib.outputs.filename }} godot/default/python/lib/python39.zip
          unzip -t godot/default/python/lib/python39.zip
          mv default/data/art godot/assets/
          mv default/data/fonts godot/assets/
          mv default/data/sound godot/assets/
          mv default/scripting godot/default/
          mv default/stringtables godot/default/
      - name: Dowload binaries
        uses: actions/download-artifact@v4
        with:
          name: android-binaries
          path: godot/bin/
      - name: Build
        uses: bend-n/godot-actions/.github/actions/export-android@main
        env:
          GODOT_VERSION: 3.5.2
          NAME: freeorion
          PROJECT_PATH: godot
```

### Logs

2025-02-08T07:05:44.7197403Z Current runner version: '2.322.0'
2025-02-08T07:05:44.7221935Z ##[group]Operating System
2025-02-08T07:05:44.7222810Z Ubuntu
2025-02-08T07:05:44.7223350Z 22.04.5
2025-02-08T07:05:44.7223848Z LTS
2025-02-08T07:05:44.7224349Z ##[endgroup]
2025-02-08T07:05:44.7224893Z ##[group]Runner Image
2025-02-08T07:05:44.7225463Z Image: ubuntu-22.04
2025-02-08T07:05:44.7226050Z Version: 20250202.1.0
2025-02-08T07:05:44.7227114Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20250202.1/images/ubuntu/Ubuntu2204-Readme.md
2025-02-08T07:05:44.7228522Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20250202.1
2025-02-08T07:05:44.7229535Z ##[endgroup]
2025-02-08T07:05:44.7230080Z ##[group]Runner Image Provisioner
2025-02-08T07:05:44.7230668Z 2.0.422.1
2025-02-08T07:05:44.7231295Z ##[endgroup]
2025-02-08T07:05:44.7232374Z ##[group]GITHUB_TOKEN Permissions
2025-02-08T07:05:44.7234212Z Contents: read
2025-02-08T07:05:44.7234793Z Metadata: read
2025-02-08T07:05:44.7235544Z Packages: read
2025-02-08T07:05:44.7236213Z ##[endgroup]
2025-02-08T07:05:44.7238268Z Secret source: Actions
2025-02-08T07:05:44.7239092Z Prepare workflow directory
2025-02-08T07:05:44.7625184Z Prepare all required actions
2025-02-08T07:05:44.7662339Z Getting action download info
2025-02-08T07:05:44.9261430Z Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
2025-02-08T07:05:45.0033291Z Download action repository 'bend-n/godot-actions@main' (SHA:287aaf38105bb89f555ca6fb911e82e66c0b5b59)
2025-02-08T07:05:45.2161281Z Download action repository 'suisei-cn/actions-download-file@v1.3.0' (SHA:00510f25d58df4c37b4ad4b9b0a61b37485964f9)
2025-02-08T07:05:45.4699318Z Download action repository 'actions/download-artifact@v4' (SHA:fa0a91b85d4f404e444e00e005971372dc801d16)
2025-02-08T07:05:45.7269255Z Getting action download info
2025-02-08T07:05:45.8261082Z Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
2025-02-08T07:05:45.8972193Z Download action repository 'actions/setup-python@v4' (SHA:65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236)
2025-02-08T07:05:46.0551584Z Getting action download info
2025-02-08T07:05:46.1435275Z Getting action download info
2025-02-08T07:05:46.2973907Z Getting action download info
2025-02-08T07:05:46.4241398Z ##[error]This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

### Version

main
