### ISSUE TITLE
(test bug report template)

### ISSUE THREAD

**Issue by bend-n** [bend-n/godot-actions#3]
### What happened?

A bug happened!
NO SKY SHOULD FALL!

### Workflow

```YAML
name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
  - bendn
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: What happened?
      value: "A bug happened!"
      placeholder: The sky fell!
      description: Also, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      render: YAML
      label: Workflow
      description: The workflow your using
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: The logs generated from the workflow, preferably a link to the run.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Version
      description: The version that you are using
      placeholder: main
      value: main
    validations:
      required: true
```

### Logs

alwokaokl
xdle
elakwooksol
a
akwjdsia

### Version

main
