### ISSUE TITLE
Butler not pushing all artifacts to itch.io

### ISSUE THREAD

**Issue by lfkdev** [bend-n/godot-actions#5]
### What happened?

Butler is not uploading all jobs to itch.io, in my case only web. 

### Workflow

```YAML
jobs:
  export:
    uses: bend-n/godot-actions/.github/workflows/callable-export.yml@main
    with:
      godot-version: 3.5
      image: ghcr.io/bend-n/godot-2d:3.5
      export-name: ${{ github.event.repository.name }}
      platforms: "${{ github.event.inputs.release_platform }}"
      project-root-path: "."
      github-pages: "true"
      itch-path: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
    secrets: # secrets
      butler-api-key: ${{ secrets.BUTLER_API_KEY }}
      android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      android-keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
```

### Logs
```
No artifact name specified, downloading all artifacts
Creating an extra directory for each artifact that is being downloaded
starting download of artifact android : 1/3
Total number of files that will be downloaded: 2
Total file count: 2 ---- Processed file #1 (50.0%)
starting download of artifact web : 2/3
Total number of files that will be downloaded: 8
Total file count: 8 ---- Processed file #7 (87.5%)
starting download of artifact windows : 3/3
Total number of files that will be downloaded: 1
There were 3 artifacts downloaded
Artifact android was downloaded to /home/runner/work/idle-village/idle-village/android
Artifact web was downloaded to /home/runner/work/idle-village/idle-village/web
Artifact windows was downloaded to /home/runner/work/idle-village/idle-village/windows
Artifact download has finished successfully
Run jdno/setup-butler@v1
butler-version has not been set. Defaulting to 'latest'.
Platform has been discovered as 'linux'.
Architecture has been discovered as 'amd64'.
Downloading butler from https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default...
Extracting butler...
/usr/bin/unzip -o -q /home/runner/work/_temp/ee96d5c9-abed-4d35-a68b-ce3dbb97d779
Caching butler...
Cached butler to /opt/hostedtoolcache/butler/LATEST/x64.
Adding butler to PATH.
v15.21.0, built on May 11 2021 @ 18:18:40, ref 6ad656eebbb5b80bf2065644d8bf9e40a15e8276

Run function push() {
  function push() {
    channel=$1
    [[ ! -d $channel ]] && exit 0
    echo "::group::Push $channel"
    [[ $channel == mac ]] && echo -e '#!/bin/bash\ncd "$(dirname "$0")";\nxattr -cr "$(pwd)/idle-village.app";\nopen -n -a "$(pwd)/idle-village.app"' >./mac/run.sh
    chmod +x **;
    butler push "$channel" "lfkdev/idle-village:$channel"
    echo "::endgroup::"
  }
  push "web"; push "linux"; push "windows"; 
  [[ -d mac ]] && unzip "mac/idle-village.zip" -d mac/ && rm "mac/idle-village.zip" && push "mac"
  [[ -d android ]] && rm android/*.idsig && push "android"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GODOT_VERSION: 3.5
    PROJECT_PATH: .
    NAME: idle-village
    BUTLER_API_KEY: ***
Push web
  • For channel `web`: last build is 650219, downloading its signature
  • Pushing 22.48 MiB (8 files, 0 dirs, 0 symlinks)
  ✓ Re-used 99.97% of old, added 6.68 KiB fresh data
  ✓ 3.38 KiB patch (99.99% savings)
  • Build is now processing, should be up in a bit.
  
  Use the `butler status lfkdev/idle-village:web` for more information.
```
### Version

newest, last commit: [e07f4fb](https://github.com/bend-n/godot-actions/commit/e07f4fba9b2e1acf9044c295fd26a3e45349d7fa)

**Comment by bend-n** [comment]
Hmm. Could you try running `butler status lfkdev/idle-village:web`? It seems to be pushing, according to these logs:
```
  • For channel `web`: last build is 650219, downloading its signature
  • Pushing 22.48 MiB (8 files, 0 dirs, 0 symlinks)
  ✓ Re-used 99.97% of old, added 6.68 KiB fresh data
  ✓ 3.38 KiB patch (99.99% savings)
  • Build is now processing, should be up in a bit.
```
All is well.

**Comment by bend-n** [comment]
And can you check the itch.io panel of uploads thing?

**Comment by lfkdev** [comment]
> Hmm. Could you try running `butler status lfkdev/idle-village:web`? It seems to be pushing, according to these logs:
> 
> ```
>   • For channel `web`: last build is 650219, downloading its signature
>   • Pushing 22.48 MiB (8 files, 0 dirs, 0 symlinks)
>   ✓ Re-used 99.97% of old, added 6.68 KiB fresh data
>   ✓ 3.38 KiB patch (99.99% savings)
>   • Build is now processing, should be up in a bit.
> ```
> 
> All is well.

Yes, the Web upload is working, but all the others aren't. Butler only takes the Web-Version and uploads it, but not android nor the windows version it just compiled. 
```
  push "web"; push "linux"; push "windows"; 
  [[ -d mac ]] && unzip "mac/idle-village.zip" -d mac/ && rm "mac/idle-village.zip" && push "mac"
  [[ -d android ]] && rm android/*.idsig && push "android"
```
According to this, butler should also upload android to itch.io - the android folder exists because i've got the android artifact in actions. But it stops right after it uploaded web

**Comment by bend-n** [comment]
Oh, I see. This means that `-d android/mac/linux` is false. Very strange, as the download logs seem alright.

What is `"${{ github.event.inputs.release_platform }}"`?

**Comment by lfkdev** [comment]
Yes, the download works fine but somehow it stops after web.
"${{ github.event.inputs.release_platform }}" is from my action-form:
```
name: "Full Compile + Export"
on:
 workflow_dispatch:
    inputs:
      version:
        description: 'game version (ex: 0.2)'
        type: string
        default: "0.02"
        required: true
      release_name:
        description: 'Release name, usually "stable", but can also be something like "ready for external game tester", "beta1"'
        type: string
        default: "general alpha testing"
        required: true
      release_platform:
        description: 'Which platforms to release/export for. Avaliable: windows web android mac linux (split by space)'
        type: string
        default: "windows web android"
        required: true
```
I just tested to only select android - it's not pushing at all with only android selected. Maybe theres something wrongly configured on my end? Theres a green hook beside the itch.io push action, but it didn't actually pushed anything. Looks like the -d check is evaluating to false and it just skipps everything (beside web). Any idea?

**Comment by bend-n** [comment]
Could you try adding this job to your workflow?
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          (apt-get update && apt-get install tree) || true
          tree -d || ls -R
```

**Comment by bend-n** [comment]
[I cant repro](https://github.com/bend-n/spaceshooty/actions/runs/3394241651/jobs/5642584599#step:3:85), maybe its something to do with there being a dash in the repo name? Idk. Will do some more testing tmrw.

**Comment by bend-n** [comment]
I have no clue why this is happening, but even if I do a hacky workaround thing, I think the directory's just... aren't there.

@lfkdev Can you try the job I suggested?

**Comment by lfkdev** [comment]
@bend-n sorry for being late, i'll run some more tests today!

**Comment by lfkdev** [comment]
I changed my repo to public so you can see the action; https://github.com/lfkdev/idle-village/actions/runs/3412781453

My Workflow file is now:
```yaml
name: "Full Compile + Export"
on:
 workflow_dispatch:
    inputs:
      version:
        description: 'game version (ex: 0.2)'
        type: string
        default: "0.02"
        required: true
      release_name:
        description: 'Release name, usually "stable", but can also be something like "ready for external game tester", "beta1"'
        type: string
        default: "general alpha testing"
        required: true
      release_platform:
        description: 'Which platforms to release/export for. Avaliable: windows web android mac linux'
        type: string
        default: "windows web android"
        required: true

jobs:
  export:
    uses: bend-n/godot-actions/.github/workflows/callable-export.yml@main
    with:
      godot-version: 3.5
      image: ghcr.io/bend-n/godot-2d:3.5
      export-name: ${{ github.event.repository.name }}
      platforms: "${{ github.event.inputs.release_platform }}"
      project-root-path: "."
      github-pages: "true"
      itch-path: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
    secrets: # secrets
      butler-api-key: ${{ secrets.BUTLER_API_KEY }}
      android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      android-keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          (apt-get update && apt-get install tree) || true
          tree -d || ls -R
```
