### ISSUE TITLE
Export isn't working

### ISSUE THREAD

**Issue by o01eg** [bend-n/godot-actions#8]
### What happened?

When I'm trying to export android build I get errors.

If I don't use separate setup step:
```
Setup godot
  fatal: detected dubious ownership in repository at '/__w/freeorion/freeorion'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/freeorion/freeorion
  fatal: detected dubious ownership in repository at '/__w/freeorion/freeorion'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/freeorion/freeorion
  python: can't open file '/__w/freeorion/freeorion/godot/pv.py': [Errno 2] No such file or directory
  Error: Process completed with exit code 2.
```

If I use separate setup step:

```
Setup godot
  mv: cannot stat '/root/.config/godot/editor_settings-3.tres': No such file or directory
  Error: Process completed with exit code 1.
```

### Workflow

```YAML
name: "Android build"

on:
  push:
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'
  pull_request:
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'

jobs:
  generate-godot-api:
    name: Generate Godot API
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bend-n/godot:3.5
    steps:
      - name: Setup
        uses: bend-n/godot-actions/.github/actions/setup-godot@main
        env:
          GODOT_VERSION: 3.5
      - name: Generate API file
        run: |
          timeout 1m godot --no-window --disable-render-loop --video-driver Dummy --gdnative-generate-json-api godot-api.json
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: godot-api
          path: godot-api.json
          if-no-files-found: error
          retention-days: 1
  build-android:
    name: Android ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: generate-godot-api
    strategy:
      matrix:
        arch: [x86, x86_64, armeabi-v7a, arm64-v8a]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Dowload Godot API
        uses: actions/download-artifact@v3
        with:
          name: godot-api
          path: .
      - name: Download SDK
        id: download-sdk
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v13/FreeOrionSDK_13_Android-${{ matrix.arch }}.zip
          target: ../
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r24
          add-to-path: false
      - name: Configure
        run: |
          unzip -q ../${{ steps.download-sdk.outputs.filename }} -d ..
          GODOT_API_JSON=$(realpath godot-api.json)
          mkdir build
          pushd build
          FO_SDK=$(realpath ../..)
          cmake -DANDROID_ABI=${{ matrix.arch }} -DANDROID_PLATFORM=24 -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DCMAKE_CXX_FLAGS=-std=c++14 -DANDROID_ALLOW_UNDEFINED_SYMBOLS=Off -DBUILD_SERVER=OFF -DBUILD_AI=OFF -DBUILD_CLIENT_GG=OFF -DBoost_INCLUDE_DIR=${FO_SDK}/include/ -DBoost_USE_STATIC_LIBS=On -DBoost_LIBRARY_DIR=${FO_SDK}/lib/ -DBUILD_CLIENT_GODOT=On -DICUI18N_LIBRARY=${FO_SDK}/lib/libicui18n.a -DICUUC_LIBRARY=${FO_SDK}/lib/libicuuc.a -DICUDATA_LIBRARY=${FO_SDK}/lib/libicudata.a -DICONV_LIBRARY=${FO_SDK}/lib/libiconv.so -DPYTHON_LIBRARY=${FO_SDK}/lib/libpython3.9.a -DPYTHON_INCLUDE_DIR=${FO_SDK}/include/python3.9/ -DGODOT_CUSTOM_API_FILE=${GODOT_API_JSON} ..
      - name: Build
        run: |
          pushd build
          cmake --build . -- -j2
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: android-binaries
          path: godot/bin/
          if-no-files-found: error
          retention-days: 1
  export-android:
    name: Export Android
    runs-on: ubuntu-latest
    needs: build-android
    container:
      image: ghcr.io/bend-n/godot:3.5
    steps:
      - name: Setup
        uses: bend-n/godot-actions/.github/actions/setup-godot@main
        env:
          GODOT_VERSION: 3.5
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Download python library
        id: download-python-lib
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v13/python39.zip
          target: ../
      - name: Place resources
        run: |
          mkdir -p godot/default/python/lib/
          cp ../${{ steps.download-python-lib.outputs.filename }} godot/default/python/lib/python39.zip
          unzip -t godot/default/python/lib/python39.zip
          mv default/data/art godot/assets/
          mv default/data/fonts godot/assets/
          mv default/data/sound godot/assets/
          mv default/scripting godot/default/
          mv default/stringtables godot/default/
      - name: Dowload binaries
        uses: actions/download-artifact@v3
        with:
          name: android-binaries
          path: godot/bin/
      - name: Build
        uses: bend-n/godot-actions/.github/actions/export-android@main
        env:
          GODOT_VERSION: 3.5
          NAME: freeorion
          PROJECT_PATH: godot
```

### Logs

With setup https://github.com/o01eg/freeorion/actions/runs/3636462372/jobs/6136623350

Without setup https://github.com/o01eg/freeorion/actions/runs/3636114345/jobs/6135944505

### Version

main
